apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-omniportal
spec:
  rules:
  - host: omniportal.k3s.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omniportal
            port:
              number: 5000